# Generated by Django 2.1 on 2018-08-05 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('categoria', models.CharField(max_length=2)),
                ('localidad', models.CharField(max_length=75)),
                ('codigo_nacional_sangre', models.CharField(max_length=10, unique=True)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('direccion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Donacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sangre', models.FloatField(default=450.0)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Banco', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Donante',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('identificacion', models.CharField(max_length=60, unique=True)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('rh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3)),
                ('grupo_sanguineo', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=9)),
                ('estatura', models.FloatField(null=True)),
                ('peso', models.FloatField(null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('ciudad_domicilio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donante_ciudad_domicilio', to='donaciones.Ciudad')),
                ('ciudad_nacimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donante_ciudad_nacimiento', to='donaciones.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Identificacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rh', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=3, unique=True)),
                ('grupo_sanguineo', models.CharField(choices=[('Positivo', 'Positivo'), ('Negativo', 'Negativo')], max_length=9, unique=True)),
                ('cantidad_sangre', models.FloatField(default=0.0)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Banco', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='donante',
            name='tipo_identificacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Identificacion'),
        ),
        migrations.AddField(
            model_name='donacion',
            name='donante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Donante'),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Departamento'),
        ),
        migrations.AddField(
            model_name='banco',
            name='ciudad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Ciudad'),
        ),
    ]
