# Generated by Django 2.1 on 2018-08-05 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('donaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donacion',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Banco'),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='donaciones.Banco'),
        ),
    ]
